name = "dynamic-org-ai"
compatibility_date = "2025-01-15"
pages_build_output_dir = "./build/client"

[site]
bucket = "./build/client"

[build]
command = "pnpm build"

[vars]
PACKAGE_NAME = "dynamic.org.ai"

# R2 bindings for content storage
[[r2_buckets]]
binding = "CONTENT"
bucket_name = "org-ai-content"

# D1 bindings for metadata and search
[[d1_databases]]
binding = "DB"
database_name = "org-ai-metadata"
database_id = "placeholder"

# Vectorize binding for semantic search
[[vectorize]]
binding = "VECTORIZE"
index_name = "org-ai-embeddings"
