import type { Occupation } from '../types/occupation.js'

/**
 * O*NET Occupations data
 * This will be generated by the import script
 */
export const occupations: Record<string, Occupation> = {}

// Tree-shakeable getters
export function getOccupation(onetCode: string): Occupation | undefined {
  return occupations[onetCode]
}

export function getAllOccupations(): Occupation[] {
  return Object.values(occupations)
}

export function getOccupationsByTitle(title: string): Occupation[] {
  const searchTerm = title.toLowerCase()
  return Object.values(occupations).filter((occ) => occ.title.toLowerCase().includes(searchTerm))
}

export function getOccupationsByJobZone(jobZone: number): Occupation[] {
  return Object.values(occupations).filter((occ) => occ.jobZone === jobZone)
}

export function getOccupationsByCodePrefix(prefix: string): Occupation[] {
  return Object.values(occupations).filter((occ) => occ.onetCode.startsWith(prefix))
}
