/**
 * Data exports for tech.org.ai
 *
 * This file exports data generated by the import script (scripts/import.ts)
 * Run: pnpm import (from within tech.org.ai directory)
 */

export * from './technologies.js'
