import type { Property } from '../types/base.js'

/**
 * Schema.org properties data
 * This file will be generated by the import script
 */
export const properties: Record<string, Property> = {}

// Export individual property getters for tree-shaking
export function getProperty(name: string): Property | undefined {
  return properties[name]
}

export function getAllProperties(): Property[] {
  return Object.values(properties)
}

export function getPropertiesByDomain(domain: string): Property[] {
  return Object.values(properties).filter((p) => p.domainIncludes?.includes(domain))
}

export function getPropertiesByRange(range: string): Property[] {
  return Object.values(properties).filter((p) => p.rangeIncludes?.includes(range))
}
