import type { Type } from '../types/base.js'

/**
 * Schema.org types data
 * This file will be generated by the import script
 */
export const types: Record<string, Type> = {}

// Export individual type getters for tree-shaking
export function getType(name: string): Type | undefined {
  return types[name]
}

export function getAllTypes(): Type[] {
  return Object.values(types)
}

export function getTypesBySubType(subType: string): Type[] {
  return Object.values(types).filter((t) => t.subTypeOf?.includes(subType))
}
